config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # resources :books
  get 'books/new'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
   # .../books/1 や .../books/3 に該当する
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end
  def new
    @list = Book.new 
  end

  def create
     @list = Book.new(book_params)
    if @list.save
      redirect_to book_path(@list.id)
    else
      @lists = Book.all
      render :index
    end
    # １. データを受け取り新規登録するためのインスタンス作成
    # 2. データをデータベースに保存するためのsaveメソッド実行
    # 3. フラッシュメッセージを定義し、詳細画面へリダイレクト
    flash[:notice] = "投稿が成功しました"
  end
  
  def index
     @lists = Book.all
     @list = Book.new 
  end

  def show
    @list = Book.find(params[:id])
  end

  def edit
    @list = Book.find(params[:id])
  end
  
  def destroy
    list = Book.find(params[:id])  # データ（レコード）を1件取得
    list.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト  
  end
  
  def update
    @list = Book.find(params[:id])
    if @list.update(book_params)
      redirect_to book_path(@list.id)  
    else
        render :edit
    end
  end

   private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new 
  end

  def create
     @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
    # １. データを受け取り新規登録するためのインスタンス作成
    # 2. データをデータベースに保存するためのsaveメソッド実行
    # 3. フラッシュメッセージを定義し、詳細画面へリダイレクト
    flash[:notice] = "投稿が成功しました"
  end
  
  def index
     @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end
  
  def destroy
    list = List.find(params[:id])  # データ（レコード）を1件取得
    list.destroy  # データ（レコード）を削除
    redirect_to '/lists'  # 投稿一覧画面へリダイレクト  
  end
  
   private
  # ストロングパラメータ
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1>編集画面</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>件のerrorが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @list do |f| %>

  <h4>本のタイトル</h4>
  <%= f.text_field :title %>
  
  <h4>感想</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book' %>
  
  
<% end %>

<%= link_to "Show", book_path(@list.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @lists.each do |list| %>
  <tbody>
    <tr>
      <td><%= list.title%></td>
      <td><%= list.body%></td>
      <td><%= link_to "show", book_path(list.id) %></td>
      <td><%= link_to "edit", edit_book_path(list.id) %></td>
      <td><%= link_to "Destroy", destroy_book_path(list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    </tr>


  <!--<p>本のタイトル</p>-->
  <!--<span>-->
  <!--   %= link_to list.title, book_path(list.id) %>-->
  <!--</span>-->

<% end %>

</table>

<div>
  <%= flash[:notice] %>
</div>

<h2>New books</h2>
<%= form_with model: Book.new do |f| %>

<!-- form_with部分 -->
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のerrorが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <h4>本のタイトル</h4>
  <%= f.text_field :title %>

  <h4>感想</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/new.html.erb
<div>
  <%= flash[:notice] %>
</div>

<h1>新規投稿</h1>
<%= form_with model: Book.new do |f| %>

<!-- form_with部分 -->
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のerroが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <h4>本のタイトル</h4>
  <%= f.text_field :title %>
	
  <h4>感想</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
  
<% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<p id="notice">Book was successfully created.</p>

<h2>本のタイトル</h2>
<p><%= @list.title %></p>

<h2>感想</h2>
<p><%= @list.body %></p>

<%= link_to "edit", edit_book_path(@list.id) %>
<%= link_to "back", books_path %>

app/views/books/top.html.erb
<h1>Books#top</h1>
<p>Find me in app/views/books/top.html.erb</p>

app/views/homes/top.html.erb
<html>
 <body>
    <h1>
    "ようこそ"    
    <strong>Bookers</strong>
    "へ!"
    </h1>
    <p>
        <strong>Bookers</strong>
        "では、さまざまな書籍に関するあなたの意見や"
    </p>
    <p>印象を共有し交換することができます</p>
    <p>
        
        <%= link_to "start", books_path %>
        
    </p>
 </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>